# NumPy training
https://numpy.org

In [1]:
import numpy as np

## Array
An array is a central data structure of the NumPy library. 

In [20]:
# initialize NumPy array from Python list
nparray = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(type(nparray)) # numpy.ndarray
print(nparray)

<class 'numpy.ndarray'>
[ 1  1  2  3  5  8 13 21]


In [19]:
# Using nested lists
nparray_nested = np.array([[1, 1, 2, 3], [5, 8, 13, 21], [34, 55, 89, 144]])
print(type(nparray_nested)) # numpy.ndarray
print(nparray_nested)

<class 'numpy.ndarray'>
[[  1   1   2   3]
 [  5   8  13  21]
 [ 34  55  89 144]]


## accessing numpy array values

In [16]:
print(nparray_nested[1])
type(nparray_nested[1]) # numpy.ndarray

[ 5  8 13 21]


numpy.ndarray

In [17]:
print(nparray_nested[1][3])
type(nparray_nested[1][3]) # numpy.int32

21


numpy.int32

https://numpy.org/doc/stable/user/absolute_beginners.html