# NumPy training
https://numpy.org <br/>
NumPy (<em>Numerical Python</em>) is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

<ul>
    <li>An array is a central data structure of the NumPy library.</li>
    <li>All of the elements in a NumPy array should be homogeneous.</li>
    <li>NumPy’s array class is called <strong>ndarray</strong>. It is also known by the alias <strong>array</strong>.</li>
    <li>A <strong>vector</strong> is an array with a single dimension.</li>
    <li>A <strong>matrix</strong> refers to an array with two dimensions.</li>
    <li>A <strong>tensor</strong> is a 3-D or higher dimensional array.</li>
    <li>In NumPy, dimensions are called <strong>axes</strong> (i.e. 2D array has 2 axes, 3D - 3 etc.).</li>
</ul>

In [1]:
import numpy as np

In [3]:
# NumPy version
print(np.__version__) # 1.23.5

1.23.5


# 1. Create an array

https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [2]:
# initialize NumPy array from Python list
nparray = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(type(nparray)) # numpy.ndarray # ndarray -> n-dimensional array
print(nparray)

<class 'numpy.ndarray'>
[ 1  1  2  3  5  8 13 21]


In [3]:
# Specifying the type of the elements in the array
nparray_float = np.array([1, 1, 2, 3, 5, 8, 13, 21], dtype = np.float64)
print(nparray_float.dtype)
print(nparray_float)

float64
[ 1.  1.  2.  3.  5.  8. 13. 21.]


In [195]:
# Using nested lists
nparray_nested = np.array([[1, 1, 2, 3], [5, 8, 13, 21], [34, 55, 89, 144]]) # 2D array with shape (3, 4)
nparray_nested_nan = np.array([[1, 1, 2, np.nan], [5, 8, 13, 21], [34, np.nan, 89, 144]]) # 2D array
nparray_nested_3D = np.array([[[1, 1, 2, 3], [5, 8, 13, 21], [34, 55, 89, 144]]]) # 3D array with shape (1, 3, 4)
print(type(nparray_nested)) # numpy.ndarray
print(f'{nparray_nested.shape=}, {nparray_nested.ndim=}')
print(nparray_nested)

<class 'numpy.ndarray'>
nparray_nested.shape=(3, 4), nparray_nested.ndim=2
[[  1   1   2   3]
 [  5   8  13  21]
 [ 34  55  89 144]]


## 1.1. Create an array using function zeros

https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

In [7]:
# By default, the dtype of the created array is float64
print(np.zeros(5)) # 1D array
nparray_zeros = np.zeros((3, 5)) # 2D array with 3 rows and 5 columns
print(nparray_zeros.dtype)
nparray_zeros

[0. 0. 0. 0. 0.]
float64


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 1.2. Create an array using function ones

https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [10]:
# By default, the dtype of the created array is float64
print(np.ones(4)) # 1D array

nparray_ones = np.ones((4, 2), dtype = np.int32) # 2D array with 4 rows and 2 columns
print(f'{nparray_ones.dtype=}')
nparray_ones

[1. 1. 1. 1.]
nparray_ones.dtype=dtype('int32')


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

## 1.3. Create an array using function empty

https://numpy.org/doc/stable/reference/generated/numpy.empty.html

In [204]:
# Creates an array whose initial content is random
    # By default, the dtype of the created array is float64
nparray_mt = np.empty((2, 2)) # 2 rows and 2 columns
print(nparray_mt.dtype)
nparray_mt

float64


array([[2.12199579e-314, 8.48798316e-314],
       [1.06099790e-313, 4.66839074e-313]])

## 1.4. Create an array using function arange

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [206]:
nparray_aranged = np.arange(start = 0, # The default start value is 0
                            stop = 101,
                            step = 25) # The default step size is 1
print(nparray_aranged.dtype)
nparray_aranged

int32


array([  0,  25,  50,  75, 100])

In [209]:
nparray_3d = np.arange(1, 101).reshape(2, 5, 10) # creates 3D array
print(type(nparray_3d))
print(f'{nparray_3d.ndim=}')
nparray_3d

<class 'numpy.ndarray'>
nparray_3d.ndim=3


array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [10]:
nparray_4d = np.arange(1, 121).reshape(2, 3, 4, 5)
print(type(nparray_4d))
print(f'{nparray_4d.ndim=}')
nparray_4d

<class 'numpy.ndarray'>
nparray_4d.ndim=4


array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

## 1.5. Create an array using function linspace

https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

In [11]:
#nparray_linsp = np.linspace(start = 0, stop = 100, num = 5)
#nparray_linsp = np.linspace(start = 0, stop = 100, num = 5, dtype = np.int32) # same as previous
nparray_linsp = np.linspace(start = 0, stop = 101, num = 25) # num = 25 -> number of elements in the array
nparray_linsp # 1D array

array([  0.        ,   4.20833333,   8.41666667,  12.625     ,
        16.83333333,  21.04166667,  25.25      ,  29.45833333,
        33.66666667,  37.875     ,  42.08333333,  46.29166667,
        50.5       ,  54.70833333,  58.91666667,  63.125     ,
        67.33333333,  71.54166667,  75.75      ,  79.95833333,
        84.16666667,  88.375     ,  92.58333333,  96.79166667,
       101.        ])

In [214]:
101/24

4.208333333333333

## 1.6. Create an array using function eye

https://numpy.org/doc/stable/reference/generated/numpy.eye.html

In [12]:
np.eye(5) # 2D array with ones on the diagonal and zeros elsewhere. Identity [square] matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 1.7. Create an array using random methods

https://numpy.org/doc/stable/reference/random/index.html

In [16]:
np.random.rand(5, 3) # 2D array with 5 rows and 3 columns.
# Unlike for np.zeros, np.ones ... where you defined a tuple to get n-dimensional array, here each parameter is a dimension.

array([[0.65117509, 0.87357348, 0.22449597],
       [0.96870344, 0.3581739 , 0.56483053],
       [0.63952608, 0.83194617, 0.91971677],
       [0.42897035, 0.23580245, 0.47597907],
       [0.6483936 , 0.41658459, 0.53546833]])

# 2. Accessing numpy array values

In [215]:
print(nparray_nested)
print(nparray_nested[1])
type(nparray_nested[1]) # numpy.ndarray

[[  1   1   2   3]
 [  5   8  13  21]
 [ 34  55  89 144]]
[ 5  8 13 21]


numpy.ndarray

In [13]:
print(nparray_nested[1][3])
type(nparray_nested[1][3]) # numpy.int32

21


numpy.int32

https://numpy.org/doc/stable/user/absolute_beginners.html

# 3. Attributes of an ndarray object

In [14]:
# The dimensions of the array
print(nparray.shape)
print(nparray_nested.shape) # (No of rows, No of columns)

(8,)
(3, 4)


In [15]:
# The number of axes (dimensions) of the array
print(nparray.ndim)
print(nparray_nested.ndim)

1
2


In [16]:
# The total number of elements of the array
print(nparray.size)
print(nparray_nested.size)
print(nparray_nested_nan.size) # NaN values do not impact size

8
12
12


In [17]:
# An object describing the type of the elements in the array
print(nparray.dtype)
print(nparray_nested.dtype)
print(nparray_nested_nan.dtype)

int32
int32
float64


In [18]:
# The size in bytes of each element of the array
print(nparray.itemsize) # 4 bytes
print(nparray_nested.itemsize) # 4 bytes
print(nparray_nested_nan.itemsize) # 8 bytes

4
4
8


In [19]:
# The buffer containing the actual elements of the array
print(nparray.data)
print(nparray_nested.data)
print(nparray_nested_nan.data)

# 4. Change array
## 4.1. Sorting

In [ ]:
help(np.sort)

In [218]:
# sort(a, axis=-1, kind=None, order=None)
    # axis: Axis along which to sort.
    # kind: {'quicksort', 'mergesort', 'heapsort', 'stable'}
    # order: 
nparray1 = np.arange(20,0,-1)
print(nparray1)
np.sort(nparray1) # do not sort in-place (use np.ndarray.sort for in-place sorting or see bellow)
#nparray1.sort() # sort an array in-place
#print(nparray1)
#print(np.sort(nparray1))
nparray1

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [80]:
# Sort an array in-place
nparray2 = np.array([4, 4, 5, 1, 0, -4, 22, 9])
np.sort(nparray2)
print(nparray2)
np.ndarray.sort(nparray2) # or
#nparray2.sort()
print(nparray2)

[ 4  4  5  1  0 -4 22  9]
[-4  0  1  4  4  5  9 22]


In [224]:
# Sorting, defining axis
nparray_2D  = np.array([[5, 3, 9], [12, 0, 22], [54, 12, 9], [1, 5, 22]])
nparray_2D_nan  = np.array([[5, 3, np.nan], [12, 0, 22], [np.nan, 12, 9], [1, 5, 22]])
print(nparray_2D)
print(nparray_2D.shape)
print('sort nparray_2D')
print(np.sort(nparray_2D, axis = 0))
print('sort nparray_2D_nan')
print(np.sort(nparray_2D_nan, axis = 0))

print(np.sort(nparray_3d, axis = -1)) # sort by last dim
print(np.sort(nparray_3d)) # same as prev


[[ 5  3  9]
 [12  0 22]
 [54 12  9]
 [ 1  5 22]]
(4, 3)
sort nparray_2D
[[ 1  0  9]
 [ 5  3  9]
 [12  5 22]
 [54 12 22]]
sort nparray_2D_nan
[[ 1.  0.  9.]
 [ 5.  3. 22.]
 [12.  5. 22.]
 [nan 12. nan]]
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]]]
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]


In [62]:
# Sort all 2D elements in ASC order
nparray_2D_v2 = np.sort(nparray_2D.flatten()).reshape(4, 3) # flatten converts 2D into 1D
print(nparray_2D_v2)

[[ 0  1  3]
 [ 5  5  9]
 [ 9 12 12]
 [22 22 54]]


In [232]:
# Descending order

print('1D option 1: minus')
#print(nparray_3d[0][0])
print(-np.sort(-nparray_3d[0][0]))
print('1D option 2: [::-1]')
print(np.sort(nparray_3d[0][0])[::-1])
print('1D option 3: flip')
print(np.flip(nparray_3d[0][0])) # 
c = np.sort(np.array([1,2,4,4,3,1,5]))
print(np.flip(c))

1D option 1: minus
[10  9  8  7  6  5  4  3  2  1]
1D option 2: [::-1]
[10  9  8  7  6  5  4  3  2  1]
1D option 3: flip
[10  9  8  7  6  5  4  3  2  1]
[5 4 4 3 2 1 1]


In [238]:
print(nparray_3d.shape)
#print(type(nparray_3d))
#nparray_3d[0][0][0] = 1
print(nparray_3d)

print('3D option 1: minus')
print(-np.sort(-nparray_3d, axis = 1))
print('3D option 2: [::-1]')
print(np.sort(nparray_3d, axis = 1)[:,::-1,:])
print('3D option 3: flip')
print(np.flip(nparray_3d, axis = 1)) # use axis to sort particular axis

(2, 5, 10)
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]]]
3D option 1: minus
[[[ 41  42  43  44  45  46  47  48  49  50]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 11  12  13  14  15  16  17  18  19  20]
  [  1   2   3   4   5   6   7   8   9  10]]

 [[ 91  92  93  94  95  96  97  98  99 100]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 51  52  53  54  55  56  57  58  59  60]]]
3D option 2: [::-1]
[[[ 41  42  43  44  45  46  47  48  49  50]
  [ 31  32  33  34

## 4.2. Reshape

In [ ]:
help(np.reshape)
# reshape(a, newshape, order='C')
    # order: {'C', 'F', 'A'}

In [126]:
nparr1 = np.arange(10)
print(nparr1)
nparr2D = nparr1.reshape(2, 5)
print(nparr2D.ndim)
print(nparr2D)

[0 1 2 3 4 5 6 7 8 9]
2
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [240]:
nparr2 = np.reshape(a = nparr2D, newshape = (10,))
print(nparr2.ndim)
print(nparr2)
print(np.reshape(a = nparr2D, newshape = (5, 2)))

1
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# 5. Math operations

In [144]:
mat1 = np.arange(10).reshape(2, 5)
mat2 = np.arange(10).reshape(5, 2)
mat3 = np.arange(15, 25).reshape(2, 5)
mat4 = np.array([[0, 2], [5, 10]])
mat5 = np.array([[7, 3], [5, 13]])
print('mat1')
print(mat1)
print('mat2')
print(mat2)
print('mat3')
print(mat3)
print('mat4')
print(mat4)
print('mat5')
print(mat5)

mat1
[[0 1 2 3 4]
 [5 6 7 8 9]]
mat2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
mat3
[[15 16 17 18 19]
 [20 21 22 23 24]]
mat4
[[ 0  2]
 [ 5 10]]
mat5
[[ 7  3]
 [ 5 13]]


In [183]:
mat1 * 5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [184]:
mat1 + 5.5

array([[ 5.5,  6.5,  7.5,  8.5,  9.5],
       [10.5, 11.5, 12.5, 13.5, 14.5]])

In [189]:
print('mat1 + mat3')
print(f'{mat1.shape=}, {mat2.shape=} and {mat3.shape=}')
print(mat1 + mat3)

#print(mat1 + mat2) # ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

mat1 + mat3
mat1.shape=(2, 5), mat2.shape=(5, 2) and mat3.shape=(2, 5)
[[15 17 19 21 23]
 [25 27 29 31 33]]


In [242]:
print('mat1 * mat3')
print(mat1 * mat3)
#print(np.dot(a = mat1, b = mat3)) # ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)

print('mat4 * mat5')
print(mat4 * mat5)

print('dot product: mat4 and mat5')
print(np.dot(a = mat4, b = mat5))

print('dot product: mat1 and mat2')
print(np.dot(a = mat1, b = mat2))

print('dot product: mat2 and mat1')
print(np.dot(a = mat2, b = mat1))

mat1 * mat3
[[  0  16  34  54  76]
 [100 126 154 184 216]]
mat4 * mat5
[[  0   6]
 [ 25 130]]
dot product: mat4 and mat5
[[ 10  26]
 [ 85 145]]
dot product: mat1 and mat2
[[ 60  70]
 [160 195]]
dot product: mat2 and mat1
[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [245]:
print(mat1)
print(mat1.sum())
print('sum array elements: axis = 0')
print(mat1.sum(axis = 0)) # 1D
print('sum array elements: axis = 1')
print(mat1.sum(axis = 1)) # 1D
print('sum 3D array elements: axis = 1')
print(nparray_3d)
print(nparray_3d.sum(axis = 1)) # 2D
# Same as
#print(nparray_3d[0])
a = nparray_3d[0].sum(axis = 0)
b = nparray_3d[1].sum(axis = 0)
print(np.concatenate((a, b)).reshape(2,10))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45
sum array elements: axis = 0
[ 5  7  9 11 13]
sum array elements: axis = 1
[10 35]
sum 3D array elements: axis = 1
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]]]
[[105 110 115 120 125 130 135 140 145 150]
 [355 360 365 370 375 380 385 390 395 400]]
[[105 110 115 120 125 130 135 140 145 150]
 [355 360 365 370 375 380 385 390 395 400]]


In [193]:
print(nparray_3d.sum(axis = 1).max(axis=1))

[150 400]
